### ISSUE TITLE
npm run dev时出错

### ISSUE THREAD

**Issue by ericting** [go-cqhttp/node#10]
![image](https://user-images.githubusercontent.com/29013507/116517960-4229da80-a902-11eb-9d59-73dc0284fd9a.png)

Error: connect ECONNREFUSED 0.0.0.0:6700
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
Emitted 'error' event on WebSocket instance at:
    at ClientRequest.<anonymous> (C:\Users\Administrator\Desktop\nodebot\node_modules\ws\lib\websocket.js:579:15)
    at ClientRequest.emit (events.js:315:20)
    at Socket.socketErrorListener (_http_client.js:469:9)
    at Socket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -4078,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '0.0.0.0',
  port: 6700
}
[nodemon] app crashed - waiting for file changes before starting...

**Comment by zhuweiyou** [comment]
要先下载和跑起来 https://github.com/Mrs4s/go-cqhttp/releases ,
 再运行这个项目

请根据 [README](https://github.com/go-cqhttp/node#%E5%90%AF%E5%8A%A8) 一步一步来

**Comment by ericting** [comment]
好像可以了，go-cqhttp放在根目录了。。
