### ISSUE TITLE
运行 npm run dev时报错

### ISSUE THREAD

**Issue by Learntotolearn** [go-cqhttp/node#20]
报错如下：
```

> dev
> cross-env NODE_ENV=development nodemon index.js

[nodemon] 2.0.16
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node index.js`
/root/node/node_modules/@pipcook/boa/lib/index.js:83
    const pyo = wrap(pyInst.import(name));
                                  ^

TypeError: ModuleNotFoundError: No module named 'wordcloud'
    at Object.import (/root/node/node_modules/@pipcook/boa/lib/index.js:83:35)
    at Object.<anonymous> (/root/node/plugin/hot/word-cloud.js:6:33)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/root/node/plugin/hot/service.js:3:19)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
[nodemon] app crashed - waiting for file changes before starting...

```

**Comment by zhuweiyou** [comment]
看这个 https://github.com/go-cqhttp/node/tree/master/plugin/hot 安装 wordcloud.

需要python环境

**Comment by Learntotolearn** [comment]
我重新拉取了项目，配置的账号。在运行npm run dev 时遇到这个错误：
```
> dev
> cross-env NODE_ENV=development nodemon index.js

[nodemon] 2.0.16
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node index.js`
node:events:505
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 0.0.0.0:6700
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)
Emitted 'error' event on WebSocket instance at:
    at emitErrorAndClose (/root/node/node_modules/ws/lib/websocket.js:874:13)
    at ClientRequest.<anonymous> (/root/node/node_modules/ws/lib/websocket.js:736:5)
    at ClientRequest.emit (node:events:527:28)
    at Socket.socketErrorListener (node:_http_client:454:9)
    at Socket.emit (node:events:527:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '0.0.0.0',
  port: 6700
}
```

**Comment by zhuweiyou** [comment]
看主页的 README.md, 要先跑起来 go-cqhttp

**Comment by Learntotolearn** [comment]
登录QQ，需要扫描。但扫描会提示登录环境异常，导致登录失败。这个有办法解决吗？
![middle_img_v2_24ee36df-a5e4-439d-abf7-b2d3a32d88ag](https://user-images.githubusercontent.com/85656971/167792797-eb8e11ab-85ce-4b94-8bb2-1e2e63462e3f.jpg)
使用登录协议是iPad。

**Comment by Learntotolearn** [comment]
![image](https://user-images.githubusercontent.com/85656971/167805188-8c6361b7-5a7c-4789-9d64-4a916631a01c.png)
没有 手机验证码登录 的选择。

**Comment by zhuweiyou** [comment]
去这个项目 https://github.com/Mrs4s/go-cqhttp 的 issues 下搜相关的方案.

**Comment by Learntotolearn** [comment]
感谢，我使用代理后，重新扫码可以登录了。

> 看主页的 README.md, 要先跑起来 go-cqhttp

现在我把这个go-cqhttp跑起来了，在到项目根目录下执行 npm run dev 命令时，还是会报错。
```
> dev
> cross-env NODE_ENV=development nodemon index.js

[nodemon] 2.0.16
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node index.js`
node:events:505
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 0.0.0.0:6700
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)
Emitted 'error' event on WebSocket instance at:
    at emitErrorAndClose (/root/node/node_modules/ws/lib/websocket.js:874:13)
    at ClientRequest.<anonymous> (/root/node/node_modules/ws/lib/websocket.js:736:5)
    at ClientRequest.emit (node:events:527:28)
    at Socket.socketErrorListener (node:_http_client:454:9)
    at Socket.emit (node:events:527:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '0.0.0.0',
  port: 6700
}
```

**Comment by zhuweiyou** [comment]
6700是ws的端口, 查一下 go-cqhttp 的 device.json 配置文件里 是否正确配置了 - ws:

**Comment by zhuweiyou** [comment]
https://docs.go-cqhttp.org/guide/config.html#%E9%85%8D%E7%BD%AE%E4%BF%A1%E6%81%AF

**Comment by Learntotolearn** [comment]
> 6700是ws的端口, 查一下 go-cqhttp 的 device.json 配置文件里 是否正确配置了 - ws:

对，忘了配置这里了。现在可以正常运行了。谢谢！！ 舔狗日记的插件，需要添加什么token呀？

**Comment by zhuweiyou** [comment]
那个很久之前做的了, 可能已经失效了, 你去网上另外找接口吧

**Comment by Learntotolearn** [comment]
> 

好的。再次感谢你的回复。
